apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  replicas: 14
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: icr.io/inventory_ssal/inventory
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
